config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :books do
  	resources :post_comments, only: [:create, :destroy]
  	resources :favorites, only: [:create, :destroy]
  end

  root 'homes#top'

  get 'home/about' => 'homes#about'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy

	has_many :favorites, dependent: :destroy
	
	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :post_comments, dependent: :destroy
  has_many :favorites, source: :book_id

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_book, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @post_comment = PostComment.new
    @new_book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
    @book.user_id = current_user.id
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def correct_book
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		favorites = current_user.favorites.new(book_id: @book.id)
		favorites.save
		redirect_to request.referer
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorites = current_user.favorites.find_by(book_id: @book_id)
		favorites.destroy
		redirect_to request.referer
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		post_comment = PostComment.new(post_comment_params)
		post_comment.user_id = current_user.id
		post_comment.book_id = book.id
		post_comment.save
		redirect_to request.referer
	end

	def destroy
		PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_to request.referer
	end

	private

	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books.page(params[:page]).reverse_order
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% books.each do |book| %>
			<tr>
				<td>
					<%= link_to(book.user) do %>
					<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title, book %></td>
				<td><%= book.body %></td>

				<td>コメント数：<%= book.post_comments.count %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<% if book.errors.any? %>
			<h3><%= book.errors.count %>error occurrence</h3><!--エラーメッセ-->
			<ul>
				<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
	<% end %>

	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
		<%= render "books/newform", book: @book %>
		<%= link_to "Show", @book, class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book %></td>
						<td><%= book.body %></td>

						<td>コメント数：<%= book.post_comments.count %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
			<!--books一覧 -->

		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile' , user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform' , book: @new_book %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 60, 60, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					
					<% if @book.favorited_by?(current_user) %>
						<td>
							<%= link_to book_favorite_path(@book), method: :delete do %>
								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								<%= @book.favorites.count %>
							<% end %>
						</td>
					<% else %>
						<td>
							<%= link_to book_favorites_path(@book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= @book.favorites.count %>
							<% end %>
						</td>
					<% end %>

					<td>コメント数：<%= @book.post_comments.count %></td>
					<td>
						<% if @book.user.id == current_user.id %>
							<%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
						 <% end %>
					</td>
					<td>
						<% if @book.user.id == current_user.id %>
							<%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
						<% end %>
					</td>
				</tr>
			</table>

			<table class="show-table">
					<% @book.post_comments.each do |post_comment| %>
					<tr>
						<td>
							<%= attachment_image_tag(post_comment.user, :profile_image, :fill, 40, 40, fallback: "no-image-mini.jpg") %><br>
							<%= post_comment.user.name %>
						</td>
						<td>
							<%= post_comment.comment %>
						</td>
						<% if post_comment.user == current_user %>
							<td>
								<%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, class: "btn btn-danger " %>
							</tr>
						<% end %>
					<% end %>
			</table>

			<div class="form">
				<%= form_for [@book, @post_comment] do |f| %>
					<%= f.text_area :comment %>
					<%= f.submit "送信" %>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h2>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h2>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
		<div class="main col-md-offset-3 col-md-6">
			<p id="notice"><%= notice %></p>
			<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to 'sign up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user.id) , class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, class: 'glyphicon glyphicon-log-out logout',  method: :delete %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to 'Sign up', new_user_registration_path , class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->

    <%= yield %>

  </body>
</html>

app/views/users/_profile.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h2>User info</h2>

			<%= form_for(@user) do |f| %>
				<!-- エラーメッセージ表示-->
				<% if @user.errors.any? %>
					<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
					<ul>
						<% @user.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				<% end %>
				<!-- エラーメッセージ表示-->

				<div class="field">
					<%= f.label :name %>
					<%= f.text_field :name, class: "name" %>
				</div>

				<div class="field">
					<%= f.label :image %>
					<%= f.attachment_field :profile_image, class: "user_image" %>
				</div>

				<div class="field">
					<%= f.label :introduction %>
					<%= f.text_area :introduction, class: "introduction" %>
				</div>

				<div class="actions">
					<%= f.submit %>
				</div>

			<% end %>

		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tbody>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
				<!--books一覧 -->
		</div>
	</div>
</div>